<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('penilaian_semester', function (Blueprint $table) {
            $table->id();
            $table->foreignId('siswa_id')->constrained('siswas')->onDelete('cascade');
            $table->foreignId('periode_id')->constrained('periodes')->onDelete('cascade');
            $table->foreignId('dimensi_id')->constrained('dimensi_pembelajaran')->onDelete('cascade');
            $table->enum('kategori_akhir', ['BB', 'MB', 'BSH', 'BSB']);
            $table->text('narasi_auto')->nullable(); // Generated by system
            $table->text('narasi_manual')->nullable(); // Edited by teacher
            $table->boolean('is_approved')->default(false);
            $table->timestamp('approved_at')->nullable();
            $table->foreignId('approved_by')->nullable()->constrained('users');
            $table->timestamps();

            $table->unique(['siswa_id', 'periode_id',  'dimensi_id'], 'penilaian_unique');
        });
    }

    public function down()
    {
        Schema::dropIfExists('penilaian_semester');
    }
};
